### ISSUE TITLE
Configuration reference

### ISSUE THREAD

**Issue by LSTANCZYK** [rcmaehl/PowerToysMacros#12]
Is there any configuration reference about what to enter in the INI file?

**Comment by rcmaehl** [comment]
Wiki: https://github.com/rcmaehl/PowerToysMacros/wiki/Macros.ini-File-Configuration

Example File: https://github.com/rcmaehl/PowerToysMacros/blob/main/Examples/Macros.ini

If you need additional assistance, please let me know

**Comment by rcmaehl** [comment]
Apparently I never released 0.3.0.0

Whoops
