### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by LSTANCZYK** [rcmaehl/PowerToysMacros#16]
### Preflight Checklist

- [X] I checked for existing issues

### Install Type

New Install

### Steps to reproduce

1. Downloaded the release
2. Copied the file to Power Toys Run plugin folder
3. Closed PowerToys
4. Ran the executable
5. Received a message of successful installation 
6. Launched PowerToys
7. Opened Run settings
8. Checked the plugin list

### ✔️ Expected Behavior

Plugin is shown in the plugin list.

### ❌ Actual Behavior

Plugin is not available in the plugin list. 

### Microsoft Windows version

22H2 build 19045

### Powertoys version

0.76.2

**Comment by rcmaehl** [comment]
I'll see if I can get it added to the Plugin list, but it is uninstallable via Programs and Features

**Comment by LSTANCZYK** [comment]
So you're saying that it should still run even if it does not show in the
installed plugin list page?
That does not happen for me - no prompt list items show up for the macros
defined in the INI file.

best regards
*Lukasz Stanczyk*

<http://ukiwebdesign.com/lstanczyk>

**Comment by rcmaehl** [comment]
> So you're saying that it should still run even if it does not show in the installed plugin list page? That does not happen for me - no prompt list items show up for the macros defined in the INI file. best regards *Lukasz Stanczyk* <http://ukiwebdesign.com/lstanczyk>

Yes. PowerToysMacros registers as a URI instead of a plugin currently. Format is `macro:<macroname> [optional data]`

![image](https://github.com/rcmaehl/PowerToysMacros/assets/716581/55740188-d13c-454c-9832-df47f4f9d51c)
